spring.application.name=PROPERTY MANAGEMENT SYSTEM
spring.server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5000/propertymgt
spring.datasource.username=postgres
spring.datasource.password=1243
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Supabase S3 Configuration
supabase.s3.endpoint-url=https://yojaqlqoeachnxyoryas.storage.supabase.co/storage/v1/s3
supabase.s3.access-key=78cda157deb655336d74ee5d11f0bc93
supabase.s3.secret-key=0a1117bbf2d8071ff29ba1422b32d2a6fdec1a1f3805f7b12c8a5ea2c2560fe3
supabase.s3.region=eu-central-1
supabase.s3.bucket=images
